@startuml

left to right direction
circle Personne
circle nom
circle prenom
circle dNaiss
circle marie
circle emploi
circle create
Personne --> nom
nom --> prenom
prenom --> dNaiss
dNaiss --> marie
dNaiss --> emploi

marie -up-> emploi
emploi -left-> marie

dNaiss --> create
marie --> create
emploi --> create

@enduml
