@startuml

left to right direction
circle PersonneBuilder
circle get
circle nom
circle prenom
circle dNaiss
circle emploi
circle marie
circle create
PersonneBuilder --> get
get --> nom
nom --> prenom
prenom --> dNaiss
dNaiss --> emploi
emploi --> marie
marie --> create

@enduml
