@startuml

left to right direction
circle Personne
circle nom
circle prenom
circle dNaiss
circle emploi
circle create
Personne --> nom
nom --> prenom
prenom --> dNaiss
dNaiss --> emploi
emploi --> create

@enduml
