= Ouvert/fermé ( Open/closed)
include::default-preferences.adoc[]

== Un exemple complexe de principe Open/closed

Supposons que nous avons une application qui permet aux utilisateurs de créer des listes de tâches. Nous voulons que les utilisateurs puissent ajouter, supprimer et modifier des tâches dans leurs listes.

Une façon de mettre en œuvre cette fonctionnalité serait d'utiliser une classe `TaskList` qui contient une liste de tâches. La classe `TaskList` aurait des méthodes pour ajouter, supprimer et modifier des tâches.

Cependant, cette approche viole le principe ouvert/fermé. Si nous voulons ajouter un nouveau type de tâche, nous devrons modifier la classe `TaskList`. Cela pourrait entraîner des problèmes de compatibilité avec les versions précédentes de l'application.

Une meilleure approche serait d'utiliser un design pattern appelé `Strategy`. Le pattern `Strategy` permet d'isoler le comportement d'un objet de sa représentation.

Dans notre cas, nous pouvons utiliser le pattern `Strategy` pour créer une interface `Task` qui définit le comportement d'une tâche. Nous pouvons ensuite créer des classes concrètes qui implémentent l'interface `Task` pour différents types de tâches.

Par exemple, nous pourrions créer une classe `TaskToDo` qui représente une tâche à faire, une classe `TaskMeeting` qui représente une réunion et une classe `TaskDeadline` qui représente une tâche à réaliser avant une date limite.

La classe `TaskList` serait alors responsable de la gestion d'une liste de tâches. Elle utiliserait l'interface `Task` pour interagir avec les tâches.

.Exemple de code pour mettre en œuvre cette approche

[source,java]
----
public interface Task {
  void doTask();
}

public class TaskToDo implements Task {
  @Override
  public void doTask() {
    // Effectue la tâche à faire
  }
}

public class TaskMeeting implements Task {
  @Override
  public void doTask() {
    // Effectue la réunion
  }
}

public class TaskDeadline implements Task {
  @Override
  public void doTask() {
    // Effectue la tâche avant la date limite
  }
}

public class TaskList {
  private List<Task> tasks;

  public TaskList() {
    this.tasks = new ArrayList<>();
  }

  public void addTask(Task task) {
    this.tasks.add(task);
  }

  public void removeTask(Task task) {
    this.tasks.remove(task);
  }

  public void modifyTask(Task task, Task newTask) {
    this.tasks.remove(task);
    this.tasks.add(newTask);
  }

  public void doTasks() {
    for (Task task : this.tasks) {
      task.doTask();
    }
  }
}
----

Cette approche respecte le principe ouvert/fermé. Si nous voulons ajouter un nouveau type de tâche, nous pouvons simplement créer une nouvelle classe qui implémente l'interface `Task`. Nous n'avons pas besoin de modifier la classe `TaskList`.

.Exemple de code pour utiliser cette approche :
[source,java]
----
TaskList taskList = new TaskList();

taskList.addTask(new TaskToDo());
taskList.addTask(new TaskMeeting());
taskList.addTask(new TaskDeadline());

taskList.doTasks();
----

Cette approche permet d'ajouter de nouveaux types de tâches sans avoir à modifier le code existant. Cela rend l'application plus flexible et plus facile à maintenir.

Quelques autres avantages du principe Open/closed :

* Il permet de réduire le code redondant.
* Il facilite la réutilisation du code.
* Il permet d'améliorer la maintenabilité du code.

En suivant le principe Open/closed, nous pouvons créer des applications plus flexibles, plus faciles à maintenir et plus évolutives.
