= Optional en Java — Comment et quand les utiliser ?
:doctype: book
:encoding: utf-8
:lang: fr
:icons: font
:tip-caption: pass:[&#x1F441;]
:warning-caption: pass:[&#9888]
:important-caption: pass:[&#9763;]
:note-caption: pass:[&#33;]
:caution-caption: pass:[&#9761;]
:source-highlighter: rouge
:rouge-style: github
:includedir: _includes
:author: Stéphane BETTON
:email: stéphane.betton@ag2rlamondiale.fr
:toc: left
:toclevels: 6

La classe Optionnel : +
Découvrez le concept de Optional, son objectif et comment il représente la présence ou l'absence d'une valeur. Découvrez également les méthodes de la classe Optional et comment les utiliser.

[IMPORTANT]
====
En utilisant la classe Optionnel, vous pouvez améliorer la lisibilité, la maintenabilité et la gestion des erreurs de votre code Java.
====

[source,java]
----
public class Employee {
    private final String name;
    private final int age;
    private final String email;
    // constructeur
    // getters et setters
}
----

== Débuter avec Optional
Les méthodes de base de la classe Optional sont :

* [blue]**empty()** : Créer un Optional vide
* [blue]**of()** : Créer un Optional avec une valeur non null
* [blue]**ofNullable()** : Créer un Optional avec une valeur pouvant être null

=== Création

.OptionalCreate.java
[source,java]
----
import java.util.Optional;

public class OptionalCreate {
     /**
     * Retourne un Optional<Employee> avec la méthode ofNullable
     *
     * @param employee peut-être null
     * @return Optional<Employee>
     */
    public Optional<Employee> getEmployeeWithOfNullable(Employee employee) {
        return Optional.ofNullable(employee);
    }

    /**
     * Retourne un Optional<Employee> avec la méthode of
     *
     * @param employee ne peut pas être null
     * @return Optional<Employee>
     */
    public Optional<Employee> getEmployeeWithOf(Employee employee) {
        return Optional.of(employee);
    }

    /**
     * Retourne un Optional<Employee> avec la méthode empty
     *
     * @return Optional<Employee>
     */
    public Optional<Employee> getEmployeeWithEmpty() {
        return Optional.empty();
    }
}
----
=== Tests
.OptionalCreateTest.java
[source,java]
----
import org.assertj.core.api.Assertions;
import org.hussard.data.Employee;
import org.junit.jupiter.api.Test;

import java.util.Optional;

import static org.assertj.core.api.AssertionsForClassTypes.assertThat;
import static org.assertj.core.api.AssertionsForClassTypes.catchThrowable;

class OptionalCreateTest {
    /**
     * Test de la méthode ofNullable
     * avec un paramètre null
     * En utilisant la methode OfNullable si le paramètre est null
     * l'Optional retourné est vide
     * Ce qui peut être utile pour retourner une valeur par défaut
     * Et éviter de retourner null
     */
    @Test
    void getEmployeeNameWithOfNullable_ParamNull() {
        OptionalCreate optionalCreate = new OptionalCreate();
        Optional<Employee> employeeOptional = optionalCreate.getEmployeeWithOfNullable(null);
        assertThat(employeeOptional).isNotNull();
        assertThat(employeeOptional).isNotPresent();
        assertThat(employeeOptional).isEmpty();
    }
    /**
     * Test de la méthode ofNullable
     * avec un paramètre non null
     * En utilisant la methode OfNullable si le paramètre est non null
     * l'Optional retourné est non vide
     */
    @Test
    void getEmployeeNameWithOfNullable_ParamEmployee() {
        OptionalCreate optionalCreate = new OptionalCreate();
        Employee employee = new Employee("John", 29, "john@monmail.com");
        Optional<Employee> optionalEmployee = optionalCreate.getEmployeeWithOfNullable(employee);
        assertThat(optionalEmployee).isNotNull();
        assertThat(optionalEmployee).isPresent();
        assertThat(optionalEmployee).isNotEmpty();
    }
    /**
     * Test de la méthode Of
     * avec un paramètre null
     * si le paramètre est null alors une exception est levée
     */
    @Test
    void getEmployeeNameWithOf_ParamNull() {
        OptionalCreate optionalCreate = new OptionalCreate();
        Throwable thrown = catchThrowable(() -> optionalCreate.getEmployeeWithOf(null));
        Assertions.assertThat(thrown)
                .isInstanceOf(NullPointerException.class);
    }
    /**
     * Test de la méthode Of
     * avec un paramètre non null
     * En utilisant la methode Of si le paramètre est non null
     * l'Optional retourné est non vide
     */
    @Test
    void getEmployeeNameWithOf_ParamEmployee() {
        OptionalCreate optionalCreate = new OptionalCreate();
        Employee employee = new Employee("John", 29, "john@monmail.com");
        Optional<Employee> optionalEmployee = optionalCreate.getEmployeeWithOf(employee);
        assertThat(optionalEmployee).isNotNull();
        assertThat(optionalEmployee).isPresent();
        assertThat(optionalEmployee).isNotEmpty();
    }
    /**
     * Test de la méthode empty
     * En utilisant la methode empty
     * l'Optional retourné est vide
     * Ce qui peut être utile pour initialiser pour retourner une valeur par défaut
     * Et éviter de retourner null
     */
    @Test
    void getEmployeeNameWithEmpty_ParamNull() {
        OptionalCreate optionalCreate = new OptionalCreate();
        Optional<Employee> optionalEmployee = optionalCreate.getEmployeeWithEmpty();
        assertThat(optionalEmployee).isNotNull();
        assertThat(optionalEmployee).isNotPresent();
        assertThat(optionalEmployee).isEmpty();
    }
}
----

== Quelques méthodes de la classe Optional
* [blue]**get()** : Retourne la valeur si elle est présente, sinon lance une exception NoSuchElementException
* [blue]**ifPresentOrElse** : Exécute le bloc de code si la valeur est présente, sinon exécute le bloc de code par défaut, elle présente un intérêt dans le cas d'un traitement dans une methode de type void
* [blue]**orElseThrow** : Retourne la valeur si elle est présente, sinon lance une exception, presente un intérêt dans le cas d'un traitement dans une methode qui retourne un type mais envoie une exception si la valeur est absente
* [blue]**orElse** : Retourne la valeur si elle est présente, sinon retourne la valeur par défaut.
Presente un intérêt dans le cas d'un traitement dans une methode qui retourne un type mais envoie une valeur par défaut si la valeur est absente
* [blue]**or** : Retourne la valeur si elle est présente, sinon retourne un Optional avec la valeur par défaut.
Similarité avec la méthode orElse, la différence est que la méthode orElse retourne la valeur par défaut et la méthode or retourne un Optional avec la valeur par défaut
* [blue]**map** : Retourne un Optional avec la valeur transformée si elle est présente, sinon retourne un Optional vide, Presente un intérêt dans le cas d'un traitement(type business ou mapping par exemple) dans une methode qui retourne un type mais, envoie une valeur par défaut si la valeur est absente




.OptionalOtherMethods.java
[source,java]
----
import org.hussard.data.Employee;

import java.util.Optional;
import java.util.function.Function;

public class OptionalOtherMethods {

    public String get(Employee employee) {
        Optional<Employee> optional = Optional.ofNullable(employee);
        //sonarlint va détecter une violation de règle
        //https://rules.sonarsource.com/java/RSPEC-3655/

        //Attention si l'optional est vide une exception est levée
        return optional.get().getName();
    }

    public void ifPresentOrElse(Employee employee) {
        Optional<Employee> optional = Optional.ofNullable(employee);
        //permet de faire des traitements si l'optional est non vide
        optional.ifPresentOrElse(
                //traitements si l'optional est non vide
                e -> upperCaseName(e.getName()),
                //traitements si l'optional est vide
                this::getEmployeeNotFound);
    }

    private void getEmployeeNotFound() {
        System.out.println("Employee not found");
    }

    private void upperCaseName(String name) {
        System.out.println(name.toUpperCase());
    }
    /**
     * Retourne un Employee avec la méthode orElseThrow
    * si l'optional est vide alors on aura une exception
     * si l'optional est non vide alors on retourne l'Employee
     *
     * @param employee peut-être null
     * @return Employee
     */
    public Employee orElseThrow(Employee employee) {
        Optional<Employee> optional = Optional.ofNullable(employee);
        return optional.orElseThrow(() -> new RuntimeException("Employee not found"));
    }
    /**
     * Retourne le nom d'un Employee avec la méthode ifPresentOrElse
     * si l'optional est vide alors, on retourne un nom par défaut
     * sinon, on retourne le nom de l'Employee
     *
     * @param employee peut-être null
     * @return Employee
     */
    public String orElse(Employee employee) {
        Optional<Employee> optional = Optional.ofNullable(employee);
        return optional.map(Employee::getName).orElse("Unknown");
    }

    /**
     * Retourne le nom d'un Employee avec la méthode or
     * si l'optional est vide alors, on retourne un nom par défaut
     * sinon, on retourne le nom de l'Employee
     * @param employee peut-être null
     * @return Optional<String>
     */
    public Optional<String> or(Employee employee) {
        Optional<Employee> optional = Optional.ofNullable(employee);
        return optional.map(Employee::getName).or(() -> Optional.of("Unknown"));
    }

    /**
     * Retourne le nom d'un Employee avec la méthode ifPresentOrElse
     * si l'optional est vide alors, on retourne un nom par défaut
     * sinon, on retourne le nom de l'Employee
     * @param employee peut-être null
     * @return String
     */
    public String map(Employee employee) {
        Optional<Employee> optional = Optional.ofNullable(employee);
        return optional.map(getMapper()).orElse("Valeur par défaut");
    }

    /**
     * Mapper qui permet de transformer le nom de l'Employee en majuscule
     * si le nom est null alors on retourne "Unknown" en majuscule
     * @return Function<Employee, String>
     */
    private static Function<Employee, String> getMapper() {
        Function<Employee, String> getName = Employee::getName;
        getName = getName.andThen(String::toUpperCase);
        return getName;
    }
}
----

[source,java]
----
import org.hussard.data.Employee;

import java.util.Optional;
import java.util.function.Function;

public class OptionalOtherMethodsTest {

    public String get(Employee employee) {
        Optional<Employee> optional = Optional.ofNullable(employee);
        //sonarlint va détecter une violation de règle
        //https://rules.sonarsource.com/java/RSPEC-3655/

        //Attention si l'optional est vide une exception est levée
        return optional.get().getName();
    }

    public void ifPresentOrElse(Employee employee) {
        Optional<Employee> optional = Optional.ofNullable(employee);
        //permet de faire des traitements si l'optional est non vide
        optional.ifPresentOrElse(
                //traitements si l'optional est non vide
                e -> upperCaseName(e.getName()),
                //traitements si l'optional est vide
                this::getEmployeeNotFound);
    }

    private void getEmployeeNotFound() {
        System.out.println("Employee not found");
    }

    private void upperCaseName(String name) {
        System.out.println(name.toUpperCase());
    }
    /**
     * Retourne un Employee avec la méthode orElseThrow
    * si l'optional est vide alors on aura une exception
     * si l'optional est non vide alors on retourne l'Employee
     *
     * @param employee peut-être null
     * @return Employee
     */
    public Employee orElseThrow(Employee employee) {
        Optional<Employee> optional = Optional.ofNullable(employee);
        return optional.orElseThrow(() -> new RuntimeException("Employee not found"));
    }
    /**
     * Retourne le nom d'un Employee avec la méthode ifPresentOrElse
     * si l'optional est vide alors, on retourne un nom par défaut
     * sinon, on retourne le nom de l'Employee
     *
     * @param employee peut-être null
     * @return Employee
     */
    public String orElse(Employee employee) {
        Optional<Employee> optional = Optional.ofNullable(employee);
        return optional.map(Employee::getName).orElse("Unknown");
    }

    /**
     * Retourne le nom d'un Employee avec la méthode or
     * si l'optional est vide alors, on retourne un nom par défaut
     * sinon, on retourne le nom de l'Employee
     * @param employee peut-être null
     * @return Optional<String>
     */
    public Optional<String> or(Employee employee) {
        Optional<Employee> optional = Optional.ofNullable(employee);
        return optional.map(Employee::getName).or(() -> Optional.of("Unknown"));
    }

    /**
     * Retourne le nom d'un Employee avec la méthode ifPresentOrElse
     * si l'optional est vide alors, on retourne un nom par défaut
     * sinon, on retourne le nom de l'Employee
     * @param employee peut-être null
     * @return String
     */
    public String map(Employee employee) {
        Optional<Employee> optional = Optional.ofNullable(employee);
        return optional.map(getMapper()).orElse("Valeur par défaut");
    }

    /**
     * Mapper qui permet de transformer le nom de l'Employee en majuscule
     * si le nom est null alors on retourne "Unknown" en majuscule
     * @return Function<Employee, String>
     */
    private static Function<Employee, String> getMapper() {
        Function<Employee, String> getName = Employee::getName;
        getName = getName.andThen(String::toUpperCase);
        return getName;
    }
}
----
