:doctype: book
:encoding: utf-8
:lang: fr
:icons: font
:tip-caption: pass:[&#x1F441;]
:warning-caption: pass:[&#9888]
:important-caption: pass:[&#9763;]
:note-caption: pass:[&#33;]
:caution-caption: pass:[&#9761;]
:source-highlighter: rouge
:rouge-style: github
:includedir: _includes
:author: Stéphane BETTON
:email: stéphane.betton@ag2rlamondiale.fr
:toc: left
:toclevels: 6
== Responsabilité unique (Single responsibility)

=== Exemple de violation du principe de responsabilité :
[source,java]
----
include::../../main/java/org/hussard/pattern/singleresponsibility/violation/Article.java[]
----

Cette classe viole le principe de responsabilité unique car elle a deux responsabilités distinctes :

* Stocker les informations d'un article (titre, auteur, contenu)
* Afficher les informations d'un article

Ces deux responsabilités devraient être dans des classes ou des modules séparés. Par exemple, la classe `Article` pourrait être responsable du stockage des informations, et une autre classe `ArticleView` pourrait être responsable de l'affichage des informations.

=== Exemple de code qui respecte le principe de responsabilité unique

[source,java]
----
include::../../main/java/org/hussard/pattern/singleresponsibility/respecte/Article.java[]
----
[source,java]
----
include::../../main/java/org/hussard/pattern/singleresponsibility/respecte/ArticleView.java[]
----

Dans cet exemple, la classe `Article` est responsable du stockage des informations, et la classe `ArticleView` est responsable de l'affichage des informations. Cela permet de respecter le principe de responsabilité unique, car chaque classe a une seule responsabilité.

Voici quelques avantages du respect du principe de responsabilité unique :

* Le code est plus facile à comprendre et à maintenir.
* Le code est plus facile à tester.
* Le code est plus flexible et adaptable au changement.

Il est important de respecter le principe de responsabilité unique dans la conception et la mise en œuvre de tout code.

