= Clean architecture

:doctype: book
:encoding: utf-8
:lang: en
:toc: left
:imagesdir: images
:toclevels: 6
:source-highlighter: rouge
:rouge-style: github
//ref: ttps://www.compart.com/fr/unicode/
:tip-caption: pass:[&#x1F441;]
:warning-caption: pass:[&#9888]
:important-caption: pass:[&#9763;]
:note-caption: pass:[&#33;]
:caution-caption: pass:[&#9761;]

Dans ce package, il sera défini les différents qui composent une *clean architecture*

== Introduction
La *clean architecture* est une organisation structuruelle mais aussi une méthode de travail.

* Permet de ranger les différentes parties d'un projet dans des packages précis
* Une méthode qui demande une rigueur, du coup demande un apprentissage qui n'est pas forcément simple

== La composition
Dans cette partie, nous allons voir les éléments importants qui constituent la **clean architecture**

=== La répartition

Elle se compose en 3 parties :

* Une partie application, cette partie est le point d'entrée du backEnd.
* Une partie métier(business), celle-ci contiendra uniquement toutes les règles métiers
* Une partie infrastructure, elle aura pour but de communiquer avec les différents services de l'entreprise, tel-que : une base de données, un service, des fichiers .etc

[IMPORTANT]
Il est interdit d'avoir plus de partie

=== Les règles
Elles vont permettre de bien mettre en place l'utilisation de la solution **clean architecture**


1 ::
[WARNING]
La plus importante de toutes, il est strictement de faire communiquer un élément du package métier(business) avec les deux autres(application, architecture).

2::
33::







